// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClimaTempo.API.Data.Domain.Entities;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string SenhaHash { get; set; }

    public virtual ICollection<CidadeFavorita> CidadeFavorita { get; set; } = new List<CidadeFavorita>();
}