// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClimaTempo.AP.Domain.Entities;

public partial class Usuarios
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string SenhaHash { get; set; }
}