// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClimaTempo.Domain.Entities;

public partial class CidadeFavorita
{
    public int IdCidadeFavorita { get; set; }

    public string Nome { get; set; }

    public int IdUsuario { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}