// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClimaTempo.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClimaTempo.Infrastructure.Configurations
{
    public partial class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> entity)
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuario__5B65BF97202885B6");

            entity.HasIndex(e => e.Email, "UQ__Usuario__A9D105341A65F2AD").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SenhaHash)
                .IsRequired()
                .HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuario> entity);
    }
}
