// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClimaTempo.API.Data.Data;
using ClimaTempo.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ClimaTempo.API.Data.Data.Configurations
{
    public partial class CidadeFavoritaConfiguration : IEntityTypeConfiguration<CidadeFavorita>
    {
        public void Configure(EntityTypeBuilder<CidadeFavorita> entity)
        {
            entity.HasKey(e => e.IdCidadeFavorita).HasName("PK__CidadeFa__D47993FF83A0E973");

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.CidadeFavorita)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("FK__CidadeFav__IdUsu__2C3393D0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CidadeFavorita> entity);
    }
}
