// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClimaTempo.API.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClimaTempo.API.Data.Data.Configurations
{
    public partial class CidadesFavoritasConfiguration : IEntityTypeConfiguration<CidadesFavoritas>
    {
        public void Configure(EntityTypeBuilder<CidadesFavoritas> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__CidadesF__3214EC076EC36A7D");

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CidadesFavoritas> entity);
    }
}
