// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClimaTempo.API.Data.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClimaTempo.API.Data.Data.Configurations
{
    public partial class UsuariosConfiguration : IEntityTypeConfiguration<Usuarios>
    {
        public void Configure(EntityTypeBuilder<Usuarios> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC0701E76BEC");

            entity.HasIndex(e => e.Email, "UQ__Usuarios__A9D10534ED6973E2").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SenhaHash)
                .IsRequired()
                .HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuarios> entity);
    }
}
