// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClimaTempo.API.Domain.Entities;

public partial class CidadesFavoritas
{
    public int Id { get; set; }

    public string Nome { get; set; }
}