// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClimaTempo.API.Data.Data.Configurations;
using ClimaTempo.API.Data.Domain.Entities;
using ClimaTempo.API.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ClimaTempo.API.Data.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CidadesFavoritas> CidadesFavoritas { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CidadesFavoritasConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuariosConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
